# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pesequel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'GoogleMaps'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'Realm'
pod 'RealmSwift'
pod 'Locksmith'
pod 'SPStorkController'
end
